export const APP_ROUTES = {
  agGrid: {
    local:'/ag-grid/local',
    onDemand:'/ag-grid/on-demand',
    tree:'/ag-grid/tree'
  },
  builder:{
    designer:'/designer',
    runtimeElement:'/runtime-element'
  },
  collapse:{
    accordion:'/accordion',
    collapse:'/collapse'
  },
  dao:{
    remote:'/remote',
    sqlite:'/sqlite'
  },
  dashboard: '/dashboard',
  dataBridge: '/data-bridge',
  dataDictionary:{
    components:'/components',
    editor:'/editor',
  },
  datagrid: {
    local:'/datagrid/local',
    onDemand:'/datagrid/on-demand',
    tree:'/datagrid/tree'
  },
  draggable:{
    axisLock:'/draggable/axis-lock',
    basic:'/draggable/basic',
    cloneRever:'/draggable/clone-revert',
    groupped:'/draggable/groupped',
    snapGrid:'/draggable/snap-grid',
    sortable:'/sortable'
  },
  drawer:'/drawer',
  dropdown:'/dropdown',
  inputs:{
    basic:'/basic',
    elements:'/elements',
    filePreview:'/file-preview',
    form:'/form'
  },
  message:'/message',
  modal:{
    animated:'/modal/animated',
    simple:'/modal',
  },
  popover:{
    popover:'/popover',
    tooltip:'/popover/tooltip'
  },
  repeater:{
    offline:'/repeater/offline',
    onDemand:'/repeater/on-demand'
  },
  reports:'/reports',
  resizable:{
    basic:'/resizable',
    panels:'/resizable/panels',
  },
  scrollTrack:'/scroll-track',
  scrollable:{
    dom:'/scrollable/dom',
    template:'/scorllable/template'
  },
  slides:'/slides',
  tabs:{
    basic:'/tabs',
    window:'/tabs/window'
  },
  utils:{
    appBrowser:'/utils/app-browser',
    dataCache:'/utils/data-cache',
    dataManager:'/utils/data-manager',
    storage:'/utils/storage',
    http:'/utils/http'
  },
  webSocket:{
    client:'/web-socket/client'
  }
};
