/** Superset of AcEnumDDColumnType — adds dialect-specific types */
export enum AcEnumDbColumnType {
  // Core (maps 1:1 to AcEnumDDColumnType)
  AutoIncrement = 'AUTO_INCREMENT',
  AutoNumber    = 'AUTO_NUMBER',
  AutoIndex     = 'AUTO_INDEX',
  Blob          = 'BLOB',
  Date          = 'DATE',
  Datetime      = 'DATETIME',
  Double        = 'DOUBLE',
  Encrypted     = 'ENCRYPTED',
  Integer       = 'INTEGER',
  Json          = 'JSON',
  Password      = 'PASSWORD',
  String        = 'STRING',
  Text          = 'TEXT',
  Time          = 'TIME',
  Timestamp     = 'TIMESTAMP',
  Uuid          = 'UUID',
  YesNo         = 'YES_NO',
  Unknown       = 'UNKNOWN',
  // Extended
  BigInteger    = 'BIGINT',
  SmallInteger  = 'SMALLINT',
  Decimal       = 'DECIMAL',
  Float         = 'FLOAT',
  Boolean       = 'BOOLEAN',
  Char          = 'CHAR',
  VarChar       = 'VARCHAR',
  Binary        = 'BINARY',
  Jsonb         = 'JSONB',
  Xml           = 'XML',
  Enum          = 'ENUM',
  Custom        = 'CUSTOM',
}
