import { AcElement, AcViewChild } from "@autocode-ts/ac-runtime";
import { AcReport } from "@autocode-ts/ac-report-engine";
import { acInitBwipjsPipe } from "@autocode-ts/ac-bwipjs-pipe";
import { IAppMenuItem } from "src/_app.export";

@AcElement({
  selector: 'reports-basic-page',
  template: `
    <div class="app-page h-100 d-flex flex-column bg-secondary bg-opacity-10">
      <app-header
        [title]="'AcReport : Document Generator'"
        [dropdownItems]="dropdownItems"
      ></app-header>
      <div class="flex-fill overflow-auto p-4">
        <div class="row g-4">
          <!-- Control Panel -->
          <div class="col-lg-3">
             <div class="card shadow-sm border-0 sticky-top" style="top: 1rem;">
                <div class="card-body">
                   <h6 class="fw-bold mb-3">Report Settings</h6>
                   <div class="mb-3">
                      <label class="form-label small">Company Name</label>
                      <input type="text" class="form-control form-control-sm" [(acModel)]="data.accountee.accountee_name" (input)="generateReport()" />
                   </div>
                   <div class="mb-3">
                      <label class="form-label small">Document Title</label>
                      <input type="text" class="form-control form-control-sm" [(acModel)]="data.report_title" (input)="generateReport()" />
                   </div>
                   <div class="d-grid gap-2 mt-4">
                      <button class="btn btn-primary btn-sm" (click)="generateReport()"><i class="fa-solid fa-arrows-rotate me-2"></i> Regenerate</button>
                      <button class="btn btn-outline-secondary btn-sm" (click)="printReport()"><i class="fa-solid fa-print me-2"></i> Print Preview</button>
                   </div>
                </div>
             </div>
          </div>

          <!-- Report Preview -->
          <div class="col-lg-9">
             <div class="report-canvas p-4 bg-white shadow mx-auto" #reportContainer ac-report>
                <!-- This will be generated by AcReport -->
                 <div class="page" ac-page ac-page-size="A4" ac-page-orientation="portrait" style="padding: 40px;">
                    <div class="d-flex justify-content-between border-bottom pb-4 mb-4">
                       <div>
                          <h2 class="fw-bold text-primary mb-0">{{data.accountee.accountee_name}}</h2>
                          <div class="text-muted small">AutoCode Software Solutions</div>
                       </div>
                       <div class="text-end">
                          <h4 class="text-uppercase fw-light">{{data.report_title}}</h4>
                          <div class="fw-bold">No: INV/2026/001</div>
                          <div class="small">Date: {{data.end_date}}</div>
                       </div>
                    </div>

                    <div class="row mb-5">
                       <div class="col-6">
                          <div class="text-muted small text-uppercase mb-2">Billed To</div>
                          <h6 class="fw-bold">Client Organization Inc.</h6>
                          <div class="small">123 Business Avenue<br>New Delhi, India</div>
                       </div>
                    </div>

                    <table class="table table-bordered mb-5">
                       <thead class="bg-light">
                          <tr>
                             <th style="width: 50px;">#</th>
                             <th>Description</th>
                             <th class="text-end" style="width: 100px;">Qty</th>
                             <th class="text-end" style="width: 150px;">Amount</th>
                          </tr>
                       </thead>
                       <tbody>
                          <tr *for="let item of data.items; index as i">
                             <td>{{i + 1}}</td>
                             <td>{{item.name}}</td>
                             <td class="text-end">{{item.qty}}</td>
                             <td class="text-end">$ {{item.amount}}</td>
                          </tr>
                       </tbody>
                    </table>

                    <div class="row justify-content-end">
                       <div class="col-4">
                          <div class="d-flex justify-content-between mb-2">
                             <span>Subtotal:</span>
                             <span class="fw-bold">$ 5,240.00</span>
                          </div>
                          <div class="d-flex justify-content-between mb-2">
                             <span>Tax (18%):</span>
                             <span class="fw-bold">$ 943.20</span>
                          </div>
                          <div class="d-flex justify-content-between border-top pt-2 mt-2">
                             <h5 class="fw-bold">Total:</h5>
                             <h5 class="fw-bold text-primary">$ 6,183.20</h5>
                          </div>
                       </div>
                    </div>

                    <div class="mt-5 pt-5 border-top small text-muted text-center">
                       <p>This is a computer generated document. Barcode below for verification.</p>
                       <div class="barcode mt-3 mx-auto" style="width: fit-content;" 
                            [ac-report-barcode]="'INV-2026-001'" 
                            ac-barcode-type="code128"></div>
                    </div>
                 </div>
             </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: `
    .report-canvas {
      width: 210mm;
      min-height: 297mm;
      font-family: 'Inter', sans-serif;
    }
  `
})
export class ReportsBasicPage {
  @AcViewChild('#reportContainer') reportContainer!: HTMLElement;
  report!: AcReport;

  data = {
    accountee: { accountee_name: 'AutoCode Corp' },
    report_title: 'Tax Invoice',
    end_date: '2026-04-19',
    items: [
      { name: 'Professional Services - April', qty: 1, amount: 4500 },
      { name: 'Cloud Infrastructure Hosting', qty: 1, amount: 740 }
    ]
  };

  dropdownItems: IAppMenuItem[] = [{ label: 'Export PDF', isHeader: true }];

  acOnInit() {
    acInitBwipjsPipe();
    this.report = new AcReport({ element: this.reportContainer });
    this.generateReport();
  }

  generateReport() {
    this.report.generate({ data: this.data });
  }

  printReport() {
    window.print();
  }
}
