import { describe, it, expect } from 'vitest';
import { AcDbStore } from '../src/lib/store/ac-db-store';
import { AcDbEventBus } from '../src/lib/store/ac-db-event-bus';
import { importFromJson } from '../src/lib/io/ac-db-import-json';
import { getSqlGenerator } from '../src/lib/sql/ac-db-sql-factory';
import { AcEnumDbDialect } from '../src/lib/enums/ac-enum-db-dialect';
import { AcEnumDbColumnType } from '../src/lib/enums/ac-enum-db-column-type';
import { createSchema } from '../src/lib/models/ac-db-schema.model';

// Shared schema fixture: users table with id (PK, AI) + email (String 255, unique) + nullable bio (Text)
function buildFixture() {
  const bus = new AcDbEventBus();
  const store = new AcDbStore(bus);
  store.addTable({ tableId: 't1', schemaId: 's1', tableName: 'users' });
  store.addTable({ tableId: 't2', schemaId: 's1', tableName: 'orders' });
  store.addColumn({ columnId: 'c1', tableId: 't1', columnName: 'id',    columnType: AcEnumDbColumnType.AutoIncrement, primaryKey: true, autoIncrement: true, nullable: false, unique: false, ordinalPosition: 0 } as any);
  store.addColumn({ columnId: 'c2', tableId: 't1', columnName: 'email', columnType: AcEnumDbColumnType.String,        primaryKey: false, nullable: false, unique: true, length: 255, ordinalPosition: 1 } as any);
  store.addColumn({ columnId: 'c3', tableId: 't1', columnName: 'bio',   columnType: AcEnumDbColumnType.Text,          primaryKey: false, nullable: true, unique: false, ordinalPosition: 2 } as any);
  store.addColumn({ columnId: 'c4', tableId: 't2', columnName: 'id',      columnType: AcEnumDbColumnType.AutoIncrement, primaryKey: true, autoIncrement: true, nullable: false, ordinalPosition: 0 } as any);
  store.addColumn({ columnId: 'c5', tableId: 't2', columnName: 'user_id', columnType: AcEnumDbColumnType.Integer, primaryKey: false, nullable: false, ordinalPosition: 1 } as any);
  store.addRelationship({ relationshipId: 'r1', schemaId: 's1', label: '', type: 'one-to-many' as any,
    fromTableId: 't2', fromColumnId: 'c5', toTableId: 't1', toColumnId: 'c1',
    onDelete: 'CASCADE' as any, onUpdate: 'NO ACTION' as any });
  const schema = createSchema({ schemaId: 's1', schemaName: 'TestDB', dialect: AcEnumDbDialect.MySQL });
  return { bus, store, schema };
}

// ── MySQL ──────────────────────────────────────────────────────────────────────
describe('SQL Generator — MySQL', () => {
  it('generates CREATE TABLE with backtick quoting', () => {
    const { store, schema } = buildFixture();
    const gen = getSqlGenerator(AcEnumDbDialect.MySQL);
    const table = store.getTable('t1')!;
    const cols  = store.getTableColumns('t1');
    const sql   = gen.generateTableBlock(table, cols, [], store);
    expect(sql).toContain('`users`');
    expect(sql).toContain('`id`');
    expect(sql).toContain('NOT NULL');
    expect(sql).toContain('PRIMARY KEY');
  });

  it('maps AutoIncrement to INT AUTO_INCREMENT', () => {
    const gen = getSqlGenerator(AcEnumDbDialect.MySQL);
    expect(gen.columnTypeMap[AcEnumDbColumnType.AutoIncrement]).toBe('INT');
  });

  it('maps String to VARCHAR with length', () => {
    const gen = getSqlGenerator(AcEnumDbDialect.MySQL);
    const col = { columnType: AcEnumDbColumnType.String, length: 255, customType: '' } as any;
    expect(gen.mapColumnType(col)).toBe('VARCHAR(255)');
  });

  it('generates full script with all tables', () => {
    const { store, schema } = buildFixture();
    const gen = getSqlGenerator(AcEnumDbDialect.MySQL);
    const sql = gen.generateFullScript(schema, store);
    expect(sql).toContain('users');
    expect(sql).toContain('orders');
    expect(sql).toContain('Generated by ac-database-designer');
  });

  it('includes FK CONSTRAINT in orders table', () => {
    const { store, schema } = buildFixture();
    const gen = getSqlGenerator(AcEnumDbDialect.MySQL);
    const sql = gen.generateFullScript(schema, store);
    expect(sql).toContain('FOREIGN KEY');
    expect(sql).toContain('CASCADE');
  });
});

// ── PostgreSQL ────────────────────────────────────────────────────────────────
describe('SQL Generator — PostgreSQL', () => {
  it('generates CREATE TABLE with double-quote quoting', () => {
    const { store, schema } = buildFixture();
    const gen = getSqlGenerator(AcEnumDbDialect.PostgreSQL);
    const table = store.getTable('t1')!;
    const cols  = store.getTableColumns('t1');
    const sql   = gen.generateTableBlock(table, cols, [], store);
    expect(sql).toContain('"users"');
    expect(sql).toContain('"id"');
  });

  it('maps AutoIncrement to SERIAL', () => {
    const gen = getSqlGenerator(AcEnumDbDialect.PostgreSQL);
    const col = { columnType: AcEnumDbColumnType.AutoIncrement, autoIncrement: true, nullable: false, unique: false, primaryKey: true, defaultValue: null, customType: '' } as any;
    const def = gen.columnDef(col);
    expect(def).toContain('SERIAL');
  });

  it('maps Timestamp to TIMESTAMPTZ', () => {
    const gen = getSqlGenerator(AcEnumDbDialect.PostgreSQL);
    expect(gen.columnTypeMap[AcEnumDbColumnType.Timestamp]).toBe('TIMESTAMPTZ');
  });

  it('generates CREATE OR REPLACE TRIGGER (via function)', () => {
    const { store } = buildFixture();
    const gen = getSqlGenerator(AcEnumDbDialect.PostgreSQL);
    const trigger = { triggerId: 'trg1', triggerName: 'trg_users_ai', timing: 'AFTER', event: 'INSERT', triggerCode: '-- body', tableId: 't1', schemaId: 's1', description: '' } as any;
    const sql = gen.generateCreateTrigger(trigger, 'users');
    expect(sql).toContain('CREATE OR REPLACE FUNCTION');
    expect(sql).toContain('CREATE TRIGGER');
  });
});

// ── SQLite ────────────────────────────────────────────────────────────────────
describe('SQL Generator — SQLite', () => {
  it('uses double-quote quoting', () => {
    const { store, schema } = buildFixture();
    const gen = getSqlGenerator(AcEnumDbDialect.SQLite);
    const table = store.getTable('t1')!;
    const cols  = store.getTableColumns('t1');
    const sql   = gen.generateTableBlock(table, cols, [], store);
    expect(sql).toContain('"users"');
  });

  it('generates PRAGMA foreign_keys = ON in full script', () => {
    const { store, schema } = buildFixture();
    const gen = getSqlGenerator(AcEnumDbDialect.SQLite);
    const sql = gen.generateFullScript(schema, store);
    expect(sql).toContain('PRAGMA foreign_keys = ON');
  });

  it('maps all numeric types to INTEGER or REAL', () => {
    const gen = getSqlGenerator(AcEnumDbDialect.SQLite);
    expect(gen.columnTypeMap[AcEnumDbColumnType.Integer]).toBe('INTEGER');
    expect(gen.columnTypeMap[AcEnumDbColumnType.Double]).toBe('REAL');
  });

  it('generates DROP VIEW IF EXISTS before CREATE VIEW', () => {
    const gen = getSqlGenerator(AcEnumDbDialect.SQLite);
    const view = { viewId: 'v1', schemaId: 's1', viewName: 'v_test', viewQuery: 'SELECT 1', description: '' } as any;
    const sql = gen.generateCreateView(view);
    expect(sql).toContain('DROP VIEW IF EXISTS');
    expect(sql).toContain('CREATE VIEW');
  });
});

// ── MSSQL ─────────────────────────────────────────────────────────────────────
describe('SQL Generator — MSSQL', () => {
  it('uses bracket quoting', () => {
    const { store, schema } = buildFixture();
    const gen = getSqlGenerator(AcEnumDbDialect.MSSQL);
    const table = store.getTable('t1')!;
    const cols  = store.getTableColumns('t1');
    const sql   = gen.generateTableBlock(table, cols, [], store);
    expect(sql).toContain('[users]');
    expect(sql).toContain('[id]');
  });

  it('uses IDENTITY(1,1) for auto-increment', () => {
    const gen = getSqlGenerator(AcEnumDbDialect.MSSQL);
    const col = { columnType: AcEnumDbColumnType.AutoIncrement, autoIncrement: true, nullable: false, unique: false, primaryKey: true, defaultValue: null, customType: '' } as any;
    const def = gen.columnDef(col);
    expect(def).toContain('IDENTITY(1,1)');
  });

  it('maps String to NVARCHAR', () => {
    const gen = getSqlGenerator(AcEnumDbDialect.MSSQL);
    expect(gen.columnTypeMap[AcEnumDbColumnType.String]).toBe('NVARCHAR');
  });

  it('generates CREATE OR ALTER VIEW', () => {
    const gen = getSqlGenerator(AcEnumDbDialect.MSSQL);
    const view = { viewId: 'v1', schemaId: 's1', viewName: 'v_test', viewQuery: 'SELECT 1', description: '' } as any;
    expect(gen.generateCreateView(view)).toContain('CREATE OR ALTER VIEW');
  });
});

// ── Factory ───────────────────────────────────────────────────────────────────
describe('getSqlGenerator factory', () => {
  it('returns correct generator for each dialect', () => {
    expect(getSqlGenerator(AcEnumDbDialect.MySQL).dialect).toBe(AcEnumDbDialect.MySQL);
    expect(getSqlGenerator(AcEnumDbDialect.PostgreSQL).dialect).toBe(AcEnumDbDialect.PostgreSQL);
    expect(getSqlGenerator(AcEnumDbDialect.SQLite).dialect).toBe(AcEnumDbDialect.SQLite);
    expect(getSqlGenerator(AcEnumDbDialect.MSSQL).dialect).toBe(AcEnumDbDialect.MSSQL);
  });
});
