import { AC_DATAGRID_EVENT } from "./ac-datagrid-event.const";

export const AC_DATAGRID_HOOK = {
  ...AC_DATAGRID_EVENT,
  ApplyFilter: 'applyFilter',
  BeforeColumnDefinitionsChange: 'beforeColumnDefinitionsChange',
  BeforeDataChange: 'beforeDataChange',
  BeforeDatagridRowCreate: 'beforeDatagridRowCreate',
  BeforeGetOnDemandData: 'beforeGetOnDemandData',
  BeforeHeaderColumnCellsCreate: 'beforeHeaderColumnCellsCreate',
  BeforeRowCellsCreate: 'beforeRowCellsCreate',
  BodyInit: 'bodyInit',
  CellEditingStart: 'cellEditingStart',
  CellEditingStop: 'cellEditingStop',
  CellEditorRefresh: 'cellEditorRefresh',
  CellFocus: 'cellFocus',
  CellKeyDown: 'cellKeyDown',
  CellKeyPress: 'cellKeyPress',
  CellKeyUp: 'cellKeyUp',
  CellRendererRefresh: 'cellRendererRefresh',
  CellValueChange: 'cellValueChange',
  ColumnDefinitionsChange: 'columnDefinitionsChange',
  ColumnFilterChange: 'columnFilterChange',
  ColumnVisibilityChange: 'columnVisibilityChange',
  ColumnWidthChange: 'columnWidthChange',
  ColumnSortChange: 'columnSortChange',
  DataChange: 'dataChange',
  DatagridCellCreate: 'datagridCellCreate',
  DatagridColumnCreate: 'datagridColumnCreate',
  DatagridInit: 'datagridInit',
  DatagridRowCreate: 'datagridRowCreate',
  DataSourceTypeChange: 'datagridSourceTypeChange',
  DisplayedRowsChange: 'displayedRowsChange',
  ElementConnected: 'elementConnected',
  ElementDisconnected: 'elementDisconnected',
  ExtensionEnable: 'extensionEnable',
  FooterInit: 'footerInit',
  GetOnDemandDataSuccessCallback: 'getOnDemandDataSuccessCallback',
  HeaderInit: 'headerInit',
  HeaderColumnCellsCreate: 'headerColumnCellsCreate',
  RefreshRows: 'refreshRows',
  RowCellsCreate: 'rowCellsCreate',
  RowAdd: 'rowAdd',
  RowFocus: 'rowFocus',
  RowDelete: 'rowDelete',
  RowUpdate: 'rowUpdate',
  ShowAddButtonChange: 'showAddButtonChange',
  ShowRowNumbersChange: 'showRowNumbersChange',
  ShowSearchInputChange: 'showSearchInputChange',
  TotalRowsChange: 'totalRowsChange',
  UsePaginationChange: 'usePaginationChange'
};
